config/routes.rb
Rails.application.routes.draw do
  root to: "todos#index"
  resources :todos
  resource :session, only: [:new, :create]
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate
  	if !signed_in?
  		redirect_to new_session_path
  	end
  end

  def signed_in?
  	session[:curren_email].present?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		session[:current_email] = params[:session][:email]
		redirect_to root_path
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_filter :authenticate
	
	def index
		@todos = Todo.all
	end
	def new
		@todo = Todo.new
	end
	def create
		Todo.create(todo_params)
		redirect_to todos_path
	end

private

def todo_params
	params.require(:todo).permit(:title)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TddRspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> Todos </h1>
<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<%= link_to "Add a new todo", new_todo_path %>
<ul class="todos">
	<%= @todos.each do |todo| %>
	<li>
		<%= todo.title %>
	</li>
	<% end%>	
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
	<%= form.label :title %>
	<%= form.text_field :title %>
	<%= form.submit "Submit" %>
<% end %>